name: TerraformIntegration
on: 
  push:
    branches:
      - master

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: 'AzureCloud'
        enable-AzPSSession: true
    - run: echo "Successfully connected"
